---

- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: Upgrade all packages
  ansible.builtin.apt:
    name: "*"
    state: latest

...
