---

- name: Make sure all needed packages are installed
    ansible.builtin.dnf:
    name: "needs-restarting"
    state: latest

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest

...
